countries = {
    'Nemačka':'Germania',
    'Italija':'Italia',
    'Rumunija':'Romania',
    'Bosna i Hercegovina':'Bosnia-Erzegovina',
    'Mađarska':'Ungheria',
    'Ruska Federacija':'Fed.Russa',
    'Češka':'Rep. Ceca',
    'Severna Makedonija':'Macedonia Nord',
    'Poljska':'Polonia',
    'Slovenija':'Slovenia',
    'Bugarska':'Bulgaria',
    'Crna Gora':'Montenegro',
    'Hrvatska':'Croazia',
    'Francuska':'Francia',
    'Austrija':'Austria',
    'Kina':'Cina',
    'Holandija':'Olanda',
    'Slovačka':'Slovacchia',
    'Velika Britanija':'Gran Bretagna',
    'Sjedinjene Američke Države':'Stati Uniti',
    'Turska':'Turchia',
    'Belgija':'Belgio',
    'Španija':'Spagna',
    'Grčka':'Grecia',
    'Irak':'Iraq',
    'UKUPNO':'TOTALE'
}