words = {
    'Nerazvrstana roba':'Merce non catalogabile',
    'Industrijske mašine za opštu upotrebu,nn':'Macchine industriali per uso generale',
    'Žive životinje, osim životinja iz odseka 03':'Animali vivi',
    'Meso i prerade od mesa':'Carne e prodotti di carne',
    'Mlečni proizvodi i ptičja jaja':'Prodotti caseari e uova',
    'Ribe, ljuskari, mekušci i prerađev. od njih':'Pesce e molluschi',
    'Žitarice i proizvodi na bazi žitarica':'Cereali e prodotti',
    'Povrće i voće':'Frutta e verdura',
    'Šećer, proizvodi od šećera i med':'Zucchero, miele, prodotti di zucchero',
    "Kafa, čaj, kakao, začini i proizvodi od njih":'Caffe, te, cacao, spezie',
    'Stočna hrana (osim žita u zrnu)':'Mangimi',
    'Razni proizvodi za ishranu i prerađevine':'Vari prodotti alimentari',
    'Pića':'Bevande',
    'Duvan i proizvodi od duvana':'Tabacco e prodotti',
    'Kože i krzno, sirovi':'Pelle e pellame',
    'Uljano semenje i uljani plodovi':'Semi per oli e prodotti di olio',
    'Sirovi kaučuk,uklj.sintetički i regenerisani':'Caucciu grezzo, sintetico e rigenereato',
    'Pluta i drvo':'Pioppo e legno',
    'Tekstilna vlakna i otpaci': 'Fibre di tessuto',
    'Sirova đubriva(osim iz odseka 56) i minerali': 'Concimi naturali e minerali',
    'Metalne rude i otpaci metala':'Minerali e scarti metallici',
    'Životinjske i biljne sirove materije, nn':'Materie animali e vegetali',
    'Kameni ugalj, koks i briketi': 'Carbone',
    'Nafta, naftini derivati i srodni proizvodi':'Petrolio e prodotti petroliferi',
    'Gas, prirodni i industrijski':'Gas naturale ed industriale',
    'Životinjska ulja i masti':'Oli e grassi animali',
    'Čvrste biljne masti i ulja,sirove,rafinisane':'Oli e grassi vegetali solidi',
    'Životinjske i biljne masti i ulja, prerađeni': 'Oli e grassi animali e vegetali raffinate',
    'Organski hemijski proizvodi':'Prodotti chimici organici',
    'Neorganski hemijski proizvodi':'Prodotti chimici non organici',
    'Proizvodi za bojenje i štavljenje':'Prodotti per colorare e trattare le pelli',
    'Medicinski i farmaceutski proizvodi':'Prodotti medici e farmaceutici',
    'Eterična ulja, parfimer.i toaletni preparati':'Oli essenziali, profumi',
    'Đubriva (osim sirovih)':'Concimi non naturali',
    'Plastične materije u primarnim oblicima':'Materie plastiche primarie',
    'Plastične mase u ostalim oblicima':'Materie plastiche non primarie',
    'Hemijske materije i proizvodi,nn':'Materie e prodotti chimici',
    'Koža, proizv. od kože, nn, i obrađena krzna':'Pelle e pellame',
    'Proizvodi od kaučuka, nigde nepomenuti':'Prodotti di caucciu e gomma',
    'Proizvodi od plute i drveta(osim nameštaja)':'Prodotti di pioppo e legno (esclusi mobili)',
    'Hartija, karton i proizvodi od celuloze':'Carta, cartone, prodotti di cellulosa',
    'Predivo, tkanine i tekstilni proizvodi':'Filati, tessuti e prodotti tessili',
    'Proizvodi od nemetalnih minerala, nn':'Prodotti di minerali non metallici',
    'Gvožđe i čelik':'Ferro e acciaio',
    'Obojeni metali':'Metalli non ferrosi',
    'Proizvodi od metala, nigde nepomenuti':'Prodotti di metallo',
    'Pogonske mašine i uređaji':'Macchine motrici ed attrezzature',
    'Mašine specijalizovane za industriju':'Macchinari industriali',
    'Mašine za obradu metala':'Macchine lavorazione metallo',
    'Industrijske mašine za opštu upotrebu,nn':'Macchine industriali per uso generale',
    'Kancelarijske mašine i mašine za AOP':'Macchine per uffici e computer',
    'Telekomunikacioni i audio aparati i oprema':'Atrezzature per telecomunicazioni e audio',
    'Električne mašine, aparati i uređaji, nn':'Macchine ed atrezzature elettriche',
    'Drumska vozila (uključujući i ACV vozila)':'Veicoli',
    'Ostala transportna sredstva i oprema':'Altri mezzi di trasporto ed atrezzature',
    'Montažne zgrade; sanitarni i drugi uređaji':'Case prefabbircate, prodotti sanitari',
    'Nameštaj i delovi;posteljina,madraci,jastuci':'Mobili e articoli per arredamenti',
    'Predmeti za putovanje, ručne torbe i slično':'Prodotti per viaggiare, valigie, borse',
    'Odevni predmeti i pribor za odevanje':'Abbigliamento',
    'Obuća':'Calzature',
    'Profesionalni,naučni i kontrolni instrumenti':'Strumenti scientifici e per laboratori',
    'Fotoaparati,optič. proizv.,časovnici, satovi':'Atrezzature fotografiche, prodotti ottici, orologi',
    'Razni gotovi proizvodi, nigde nepomenuti':'Vari prodotti finali',
    'Zlato(osim ruda i koncentrata zlata)':'Oro',
    'UKUPNO':'TOTALE'


}
